Category.create!(name: 'Ilustración')
Category.create!(name: 'Fotografía y vídeo')
Category.create!(name: 'Marketing y Negocios')
Category.create!(name: 'Diseño')
Category.create!(name: 'Craft')
Category.create!(name: '3D y Animación')
Category.create!(name: 'Arquitectura y Espacios')
Category.create!(name: 'Tecnología')
Category.create!(name: 'Caligrafía y Tipografía')
