language: ruby
cache: bundler
dist: trusty
rvm:
 - 2.7.2
addons:
  postgresql: "9.4"
before_install:
 - gem install bundler --no-document
 - bundle install
script:
 - bundle exec rails db:create
 - bundle exec rails db:migrate
 - bundle exec rails test
